---
- name: Install Java
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Add Jenkins key
  shell: |
    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -

- name: Add Jenkins repo
  shell: |
    echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes