apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: krishibandhu
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::520827482778:role/eksctl-KrishiBandhu-EKS-addon-iamserviceaccou-Role1-YRTDbq1K8Zzg
