apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGODB_URI: ""
  JWT_SECRET: "jwt_secret"
  JWT_REFRESH_SECRET: "jwt_ref_secret"
  EMAIL_PASSWORD: ""
  GEMINI_API_KEY: ""
  WEATHER_API_KEY: ""

