apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://singha17200_db_user:r8nuwAZeeIsk2I94@cluster0.cxqdgln.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "jwt_secret"
  JWT_REFRESH_SECRET: "jwt_ref_secret"
  EMAIL_PASSWORD: "znsnvjiltkzgxlub"
  GEMINI_API_KEY: "AIzaSyCBfHJ9j-NxYN2IFgC9Ilo6wHujW3_0u7s"
  WEATHER_API_KEY: "3a37bf274d5764ece351dc82c400f14e"
  MARKET_PRICE_API_KEY: "579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b"
  GOV_SCHEME_API_KEY: "579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b"