apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://singha17200_db_user:HrqCJVeVtm5UHHxP@cluster0.cxqdgln.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "jwt_secret"
  JWT_REFRESH_SECRET: "jwt_ref_secret"
  EMAIL_PASSWORD: "gxnrsoylvaogeoqw"
  GEMINI_API_KEY: "AIzaSyANbtd9fhl2Jq1wawbRnwYMG5b_p4FrfbA"
  WEATHER_API_KEY: "3a37bf274d5764ece351dc82c400f14e"

