apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krishibandhu-ingress
  namespace: krishibandhu
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx 
  tls:
  - hosts:
    - krishibandhu.adtechs.xyz
    secretName: krishibandhu-tls-secret  # Cert-Manager will manage this
  rules:
  - host: krishibandhu.adtechs.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
