apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: krishibandhu
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: backend-secret   # MUST match your deployment
    creationPolicy: Owner
  data:
  - secretKey: MONGODB_URI
    remoteRef:
      key: backend-secret
      property: MONGODB_URI

  - secretKey: JWT_SECRET
    remoteRef:
      key: backend-secret
      property: JWT_SECRET

  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: backend-secret
      property: JWT_REFRESH_SECRET

  - secretKey: EMAIL_PASSWORD
    remoteRef:
      key: backend-secret
      property: EMAIL_PASSWORD

  - secretKey: GEMINI_API_KEY
    remoteRef:
      key: backend-secret
      property: GEMINI_API_KEY

  - secretKey: WEATHER_API_KEY
    remoteRef:
      key: backend-secret
      property: WEATHER_API_KEY